version: '3'

output: 'prefixed'

tasks:

  code-format:
    cmds:
      - >
        poetry run autoflake
        --exclude '{{.DIR_LOCAL}}'
        --expand-star-imports
        --in-place
        --recursive
        --remove-all-unused-imports
        --remove-duplicate-keys
        --remove-unused-variables
        --verbose
        .
      - >
        poetry run
        isort
        .
      - >
        poetry run
        black
        .
    desc: format code with autoflake, black, isort
    dir: "{{.ROOT_DIR}}"